version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: crypto-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=crypto_news
    volumes:
      - mongodb_data:/data/db
    networks:
      - crypto-network

  # MongoDB UI admin (nếu muốn quản lý trực quan)
  mongo-express:
    image: mongo-express:latest
    container_name: crypto-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - crypto-network

volumes:
  mongodb_data:
    name: crypto_mongodb_data

networks:
  crypto-network:
    name: crypto-network
    driver: bridge 